name: kaiteki_lints
version: 0.0.1

environment:
  sdk: '>=3.3.0-2.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: any
  analyzer_plugin: any
  custom_lint_builder: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
