name: kaiteki_unicode_generator
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.3.0-97.0.dev

dependencies:
  build: ^2.4.1
  json_annotation: ^4.8.0
  source_gen: ^1.4.0

dev_dependencies:
  build_test: ^2.2.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.0.0
  lints: ^3.0.0
